# Site Settings
# variables accessed via {{ site.myvariable }}
title: Michael Taleff
author: Michael Taleff
email: mtaleff@utexas.edu
description:
url: "https://taleff.github.io/"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

#generate social links in footer
social links:
  github: taleff
  linkedin: michael-taleff

# Build Settings
markdown: kramdown
highlighter: rouge
